//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMC.Services.Contacts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string OldPassword { get; set; }
        public string Mail { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<short> TheNumberOfIncorrectPassword { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<int> CheckTypeId { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> ChildGuardianId { get; set; }
        public Nullable<int> UserTypeId { get; set; }
    }
}
