//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMC.Services.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using WMC.Services.Contacts;
    
    public partial class WMCDbEntities : DbContext
    {
        public WMCDbEntities()
            : base("name=WMCDbEntities")
        {
        }

        public WMCDbEntities(string conStr)
            : base(conStr)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Menus> Menus { get; set; }
        public virtual DbSet<ParamActions> ParamActions { get; set; }
        public virtual DbSet<ParamAuthorizationPermission> ParamAuthorizationPermission { get; set; }
        public virtual DbSet<ParamAuthorizations> ParamAuthorizations { get; set; }
        public virtual DbSet<ParamControllers> ParamControllers { get; set; }
        public virtual DbSet<ParamRoleAuthorizations> ParamRoleAuthorizations { get; set; }
        public virtual DbSet<ParamRoles> ParamRoles { get; set; }
        public virtual DbSet<ParamUserTypes> ParamUserTypes { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
